application:
    build: code
    volumes:
        - ./laravel:/var/www
        - ./logs/laravel:/var/www/storage/logs

nginx:
    build: nginx
    ports:
        - "80:80"
    links:
        - php-fpm
    volumes_from:
        - application
    volumes:
        - ./logs/nginx:/var/log/nginx

mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123

redis:
    image: redis
    ports:
        - "6379:6379"

php-fpm:
    image: php:7-fpm
    ports:
        - "9000:9000"
    links:
        - mysql
